root = "."
tmp_dir = "tmp"

[build]
    bin = "bin/main.out"
    cmd = "go build -o ./bin/main.out ./cmd/main.go"
    exclude = ["tmp/*", "client/*", "bin/*"]
    include = "**/*.go"
    ignore = ["tmp/*", "bin/*", "client/*"]